service:
  port: 8080

container:
  port: 80
  imagePullPolicy: IfNotPresent
  image: ghcr.io/ldest/sre-course/api:latest

ingress:
  host: api-n-krasnov.mts.ru

deploy:
  replicas: 1
  revisionHistoryLimit: 4
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 5Mi
